### ISSUE TITLE
觀影心得回饋

### ISSUE THREAD

**Issue by azole** [anna618/hello-git#1]
謝謝你的總結，很喜歡你心得裡的這句話「專業，就是用對方聽得懂的話，去告訴他不懂的事情。」我非常地贊同，所以有時候學生找我討論問題，結束前我都會請他試試看用自己的話說一遍給我聽，藉此來判定他的理解是怎麼樣的。上課時我也很喜歡問大家問題，可以刺激大家思考與參與，所以鼓勵你上課時試著一起回答問題看看，答對答錯都無所謂的，重點是有沒有嘗試去思考看看，把知識變成自己的，一起加油～

**Comment by anna618** [comment]
好的，謝謝老師！
